/**
 * Hidden descriptions for each command.
 * These are NOT displayed in the UI but are used for search matching.
 * e.g. searching "clone a repo" will surface `git clone <url>` commands.
 */
const descriptions = {
  // ── Init ──
  'git init': 'initialize create new repository project start begin fresh setup start new project create repo from scratch',
  'git init <directory>': 'initialize create new repository in specific folder directory start project in folder',
  'git init --bare': 'initialize create bare repository server-side no working directory setup remote server repo',
  'git init --bare <directory>': 'initialize create bare repository in specific directory server setup',
  'git init -b <branch-name>': 'initialize create new repository with custom default branch name start with main or master',
  'git init --initial-branch=<branch-name>': 'initialize create new repository with custom initial branch name start with main',

  // ── Clone ──
  'git clone <url>': 'clone copy download repository repo remote url get a copy of a project download someone elses repo clone a repo from github',
  'git clone <url> <directory>': 'clone copy download repository into specific folder directory clone repo to custom folder name',
  'git clone --depth 1 <url>': 'clone shallow copy download only latest commit history fast clone without full history lightweight clone',
  'git clone --branch <branch> <url>': 'clone specific branch from repository download only one branch clone a particular branch',
  'git clone --single-branch <url>': 'clone only one branch from repository save bandwidth single branch download',
  'git clone --no-single-branch <url>': 'clone all branches from repository get every branch',
  'git clone --recurse-submodules <url>': 'clone repository including submodules nested repos clone with dependencies',
  'git clone --bare <url>': 'clone bare repository without working directory server mirror setup',
  'git clone --mirror <url>': 'clone mirror exact copy backup of remote repository full mirror backup',
  'git clone --quiet <url>': 'clone silently without output progress quiet clone no output',
  'git clone --verbose <url>': 'clone with detailed verbose output see progress details',
  'git clone --origin <name> <url>': 'clone with custom remote name instead of origin use different remote name',
  'git clone --depth 1 --branch <branch> <url>': 'clone shallow specific branch latest commit only fast download one branch',
  'git clone --depth 1 --single-branch --branch <branch> <url>': 'clone shallow single specific branch latest commit fastest way to clone one branch',

  // ── Add / Stage ──
  'git add <file>': 'stage add file to staging area index',
  'git add .': 'stage add all files current directory to staging area',
  'git add -A': 'stage add all files entire repository working tree',
  'git add --all': 'stage add all changes tracked untracked deleted files',
  'git add -p': 'stage add interactively patch mode select hunks chunks',
  'git add --patch': 'stage add interactively patch mode select hunks chunks',
  'git add -u': 'stage add only tracked modified deleted files not new',
  'git add --update': 'stage add only tracked modified deleted files not new',
  'git add -n': 'dry run preview what would be staged added',
  'git add --dry-run': 'dry run preview what would be staged added',
  'git add -f <file>': 'force stage add ignored file bypass gitignore',
  'git add --force <file>': 'force stage add ignored file bypass gitignore',
  'git add -i': 'interactive mode stage add files menu driven',
  'git add --interactive': 'interactive mode stage add files menu driven',
  'git add -e': 'edit diff before staging add manually edit patch',
  'git add --edit': 'edit diff before staging add manually edit patch',
  'git add *.js': 'stage add all javascript files by extension pattern glob',
  'git add <dir>/': 'stage add all files in specific directory folder',

  // ── Commit ──
  'git commit': 'commit save changes create snapshot record open editor save my work save progress',
  'git commit -m "<message>"': 'commit save changes with inline message quick commit with description save work with note',
  'git commit -a': 'commit all tracked modified deleted files skip staging commit everything save all changes without add',
  'git commit -am "<message>"': 'commit all tracked changes with message skip staging quick commit everything with message one liner',
  'git commit --amend': 'amend modify edit last previous commit change message fix last commit update previous commit oops wrong message',
  'git commit --amend -m "<message>"': 'amend modify edit last commit with new message change commit message fix message typo',
  'git commit --amend --no-edit': 'amend modify last commit keep same message add staged files forgot to add a file add more changes to last commit',
  'git commit -m "<message>" --allow-empty': 'commit empty no changes allow trigger CI hooks empty commit trigger pipeline deploy',
  'git commit --no-verify -m "<message>"': 'commit skip pre-commit hooks bypass validation ignore linting commit without checks',
  'git commit -S -m "<message>"': 'commit signed GPG signature verify signed commit prove identity',
  'git commit --gpg-sign -m "<message>"': 'commit signed GPG signature verify signed commit cryptographic',
  'git commit --author="<name> <email>" -m "<message>"': 'commit with different author override commit on behalf of someone else change author',
  'git commit --date="<date>" -m "<message>"': 'commit with custom date override timestamp backdate commit change commit date',
  'git commit -v': 'commit verbose show diff in editor see changes before committing review diff',
  'git commit --verbose': 'commit verbose show diff in editor see changes before committing',
  'git commit -q': 'commit quiet suppress output silent no output commit',
  'git commit --quiet': 'commit quiet suppress output silent',
  'git commit -m "<message>" -m "<body>"': 'commit with message and body description multi-line detailed commit message title and description',
  'git commit --squash <commit>': 'commit squash combine with another commit during rebase merge commits together combine into one',
  'git commit --fixup <commit>': 'commit fixup auto amend another commit during rebase auto fix previous commit',

  // ── Status ──
  'git status': 'status check state working directory staging area modified untracked',
  'git status -s': 'status short compact brief output',
  'git status --short': 'status short compact brief output',
  'git status -b': 'status show branch info tracking',
  'git status --branch': 'status show branch info tracking',
  'git status -sb': 'status short with branch info compact',
  'git status --porcelain': 'status machine readable parseable stable format',
  'git status -u': 'status show untracked files',
  'git status --untracked-files=all': 'status show all untracked files individually',
  'git status --ignored': 'status show ignored files gitignore',
  'git status --ahead-behind': 'status show ahead behind commits remote tracking',

  // ── Diff ──
  'git diff': 'diff compare changes working directory unstaged modifications',
  'git diff <file>': 'diff compare changes specific file',
  'git diff --staged': 'diff compare staged changes ready to commit index',
  'git diff --cached': 'diff compare cached staged changes index',
  'git diff HEAD': 'diff compare all changes from last commit working and staged',
  'git diff HEAD~1': 'diff compare changes with previous commit',
  'git diff <branch1> <branch2>': 'diff compare two branches differences',
  'git diff <commit1> <commit2>': 'diff compare two commits differences',
  'git diff --stat': 'diff show statistics summary files changed insertions deletions',
  'git diff --name-only': 'diff show only file names that changed',
  'git diff --name-status': 'diff show file names and status added modified deleted',
  'git diff --word-diff': 'diff show word level changes inline',
  'git diff --color': 'diff show colored output',
  'git diff --no-color': 'diff show plain text without color',
  'git diff -U<n>': 'diff show context lines around changes',
  'git diff --unified=<n>': 'diff show custom context lines around changes',
  'git diff --ignore-space-change': 'diff ignore whitespace changes',
  'git diff -w': 'diff ignore all whitespace changes',
  'git diff --ignore-all-space': 'diff ignore all whitespace completely',
  'git diff --diff-filter=<filter>': 'diff filter by change type added deleted modified',
  'git diff HEAD --name-only': 'diff show changed file names from last commit',
  'git diff --staged --stat': 'diff staged changes statistics summary',

  // ── Log ──
  'git log': 'log history view commits show timeline',
  'git log --oneline': 'log history compact one line per commit short',
  'git log --graph': 'log history visual graph branch merge tree',
  'git log --all': 'log history all branches refs',
  'git log --decorate': 'log history show branch tag references labels',
  'git log --oneline --graph --all --decorate': 'log history complete visual graph all branches decorated',
  'git log -n <number>': 'log history limit show last n commits',
  'git log -<number>': 'log history limit show last n commits',
  'git log --author="<name>"': 'log history filter by author contributor',
  'git log --since="<date>"': 'log history filter after date since',
  'git log --until="<date>"': 'log history filter before date until',
  'git log --grep="<pattern>"': 'log history search filter commit messages grep',
  'git log -p': 'log history show patch diff changes',
  'git log --patch': 'log history show patch diff changes',
  'git log --stat': 'log history show statistics files changed',
  'git log --shortstat': 'log history show brief statistics',
  'git log --name-only': 'log history show only file names',
  'git log --name-status': 'log history show file names and change status',
  'git log --follow <file>': 'log history follow file through renames',
  'git log -- <file>': 'log history specific file only',
  'git log --merges': 'log history show only merge commits',
  'git log --no-merges': 'log history exclude merge commits',
  'git log --first-parent': 'log history follow only first parent skip merges',
  'git log --pretty=format:"<format>"': 'log history custom format output',
  'git log --format="<format>"': 'log history custom format output',
  'git log --abbrev-commit': 'log history short abbreviated commit hashes',
  'git log --relative-date': 'log history show relative time ago dates',
  'git log <branch>': 'log history specific branch',
  'git log <branch1>..<branch2>': 'log history commits in branch2 not in branch1 range',
  'git log --oneline --graph --all': 'log history compact visual graph all branches',
  'git log --oneline -n 10': 'log history last 10 commits compact',
  'git log --since="2 weeks ago"': 'log history recent last two weeks',

  // ── Branch ──
  'git branch': 'branch list local branches show current see all branches what branch am i on',
  'git branch <name>': 'branch create new branch make a branch start feature branch create branch for feature',
  'git branch -a': 'branch list all local remote branches see every branch including remote',
  'git branch --all': 'branch list all local remote branches show all branches remote and local',
  'git branch -r': 'branch list remote branches only see what branches exist on remote server github',
  'git branch --remotes': 'branch list remote branches only show remote branches',
  'git branch -d <name>': 'branch delete remove safe merged delete branch after merge cleanup remove old branch',
  'git branch --delete <name>': 'branch delete remove safe merged remove old branch',
  'git branch -D <name>': 'branch delete force remove unmerged force delete branch that was not merged',
  'git branch -m <new-name>': 'branch rename move current branch change branch name rename my branch',
  'git branch -m <old-name> <new-name>': 'branch rename move specific branch change name of another branch',
  'git branch --move <old-name> <new-name>': 'branch rename move specific branch',
  'git branch -c <new-name>': 'branch copy duplicate current branch make a copy of branch',
  'git branch --copy <new-name>': 'branch copy duplicate current branch',
  'git branch -v': 'branch list with last commit verbose see branches with latest commit',
  'git branch --verbose': 'branch list with last commit info details',
  'git branch -vv': 'branch list with upstream tracking info verbose see which remote branches are tracked',
  'git branch --merged': 'branch list merged into current branch see which branches are already merged safe to delete',
  'git branch --no-merged': 'branch list not merged into current branch see unmerged branches still open',
  'git branch --contains <commit>': 'branch list branches containing specific commit find which branch has a commit',
  'git branch -u <upstream>': 'branch set upstream tracking remote link branch to remote connect branch to origin',
  'git branch --set-upstream-to=<upstream>': 'branch set upstream tracking remote link local branch to remote branch',
  'git branch --unset-upstream': 'branch remove unset upstream tracking disconnect branch from remote',
  'git branch -f <name> <commit>': 'branch force move point to specific commit move branch pointer',
  'git branch --list': 'branch list filter branches show branches',
  'git branch --list "<pattern>"': 'branch list filter by pattern glob search branches by name',

  // ── Checkout ──
  'git checkout <branch>': 'checkout switch to branch change working directory',
  'git checkout -b <new-branch>': 'checkout create and switch to new branch',
  'git checkout -B <new-branch>': 'checkout create or reset and switch to branch force',
  'git checkout -b <new-branch> <start-point>': 'checkout create new branch from specific commit point',
  'git checkout --track <remote>/<branch>': 'checkout track remote branch create local',
  'git checkout -t <remote>/<branch>': 'checkout track remote branch create local',
  'git checkout -- <file>': 'checkout discard changes restore file from index undo',
  'git checkout HEAD -- <file>': 'checkout restore file from HEAD discard changes undo',
  'git checkout <commit> -- <file>': 'checkout restore file from specific commit version',
  'git checkout -': 'checkout switch to previous branch back last',
  'git checkout --orphan <new-branch>': 'checkout create orphan branch no history clean',
  'git checkout --detach': 'checkout detached HEAD state no branch',
  'git checkout <commit>': 'checkout specific commit detached HEAD view',
  'git checkout <tag>': 'checkout specific tag version release',

  // ── Switch ──
  'git switch <branch>': 'switch change to branch modern checkout alternative',
  'git switch -c <new-branch>': 'switch create and go to new branch',
  'git switch -C <new-branch>': 'switch create or reset and go to branch force',
  'git switch -c <new-branch> <start-point>': 'switch create new branch from specific point',
  'git switch --track <remote>/<branch>': 'switch track remote branch create local',
  'git switch --detach <commit>': 'switch to detached HEAD at commit',
  'git switch --orphan <new-branch>': 'switch create orphan branch no history',
  'git switch -': 'switch to previous branch back last',
  'git switch --guess': 'switch auto guess remote branch name',

  // ── Restore ──
  'git restore <file>': 'restore discard undo changes working directory file',
  'git restore .': 'restore discard undo all changes working directory',
  'git restore --staged <file>': 'restore unstage file remove from staging index',
  'git restore --staged .': 'restore unstage all files remove from staging index',
  'git restore --source=<commit> <file>': 'restore file from specific commit version source',
  'git restore --worktree <file>': 'restore working tree file changes',
  'git restore -s <commit> <file>': 'restore file from specific commit source short',

  // ── Merge ──
  'git merge <branch>': 'merge combine integrate branch into current merge feature branch into main merge branch into master combine branches together',
  'git merge --no-ff <branch>': 'merge no fast-forward create merge commit always keep merge history visible preserve branch history',
  'git merge --ff-only <branch>': 'merge fast-forward only fail if not possible clean linear merge safe merge',
  'git merge --squash <branch>': 'merge squash combine all commits into one staging merge branch as single commit clean up messy history',
  'git merge --abort': 'merge abort cancel stop resolve conflict undo cancel merge in progress fix merge conflict give up',
  'git merge --continue': 'merge continue resume after resolving conflicts finish merge after fixing conflicts',
  'git merge -m "<message>" <branch>': 'merge with custom commit message merge branch with description',
  'git merge --strategy=<strategy> <branch>': 'merge with specific strategy recursive ours custom merge strategy',
  'git merge -X <option> <branch>': 'merge with strategy option theirs patience resolve conflicts automatically',
  'git merge --allow-unrelated-histories <branch>': 'merge unrelated histories different roots merge two completely separate repos combine unrelated projects',
  'git merge --no-commit <branch>': 'merge without auto commit review changes first preview merge before committing',
  'git merge --stat <branch>': 'merge show statistics summary see what changed in merge',
  'git merge --no-stat <branch>': 'merge without statistics summary quiet merge',
  'git merge --log <branch>': 'merge include log messages from merged commits detailed merge with commit messages',
  'git merge --no-ff -m "<message>" <branch>': 'merge no fast-forward with custom message merge branch with description keep merge commit',

  // ── Rebase ──
  'git rebase <branch>': 'rebase replay commits onto branch linear history',
  'git rebase -i HEAD~<n>': 'rebase interactive edit squash reorder last n commits',
  'git rebase -i <commit>': 'rebase interactive from specific commit edit squash',
  'git rebase --onto <newbase> <oldbase> <branch>': 'rebase move commits onto different base branch',
  'git rebase --abort': 'rebase abort cancel stop undo',
  'git rebase --continue': 'rebase continue resume after resolving conflict',
  'git rebase --skip': 'rebase skip current commit continue next',
  'git rebase --autosquash': 'rebase auto squash fixup commits',
  'git rebase --autostash': 'rebase auto stash unstash changes before after',
  'git rebase -x <command>': 'rebase exec run command after each commit',
  'git rebase --exec <command>': 'rebase exec run command after each commit',
  'git rebase --rebase-merges': 'rebase preserve recreate merge commits',
  'git rebase --preserve-merges': 'rebase preserve merge commits deprecated',
  'git rebase -i --autosquash HEAD~<n>': 'rebase interactive auto squash fixup last n commits',
  'git rebase --onto <newbase> <oldbase>': 'rebase move commits onto different base',

  // ── Push ──
  'git push': 'push upload send commits to remote repository push code to github publish changes deploy send my changes',
  'git push <remote> <branch>': 'push upload to specific remote branch push branch to github send branch to remote',
  'git push origin main': 'push upload to origin main branch push changes to main deploy to production push to github main',
  'git push origin HEAD': 'push upload current branch to origin push current branch to github send this branch',
  'git push -u <remote> <branch>': 'push set upstream tracking upload first time push new branch for first time publish branch to remote create remote branch',
  'git push --set-upstream <remote> <branch>': 'push set upstream tracking upload first time publish new branch connect branch to remote',
  'git push -f': 'push force overwrite remote history dangerous force push overwrite remote rewrite history',
  'git push --force': 'push force overwrite remote history dangerous force push after rebase amend',
  'git push --force-with-lease': 'push force safe check remote not changed safe force push protect against overwrites force push after rebase safely',
  'git push --force-with-lease=<refname>:<expect>': 'push force safe specific ref check conditional force push',
  'git push --all': 'push all branches to remote push every branch to github sync all branches',
  'git push --tags': 'push all tags to remote publish versions releases send tags to github',
  'git push --follow-tags': 'push commits and annotated tags push code and version tags together',
  'git push --no-verify': 'push skip pre-push hooks bypass push without running checks ignore hooks',
  'git push --dry-run': 'push dry run preview simulate what would happen test push see what would be pushed',
  'git push -d <remote> <branch>': 'push delete remote branch remove delete branch from github remove branch from server',
  'git push --delete <remote> <branch>': 'push delete remote branch remove delete branch from github cleanup remote',
  'git push <remote> :<branch>': 'push delete remote branch using refspec remove branch from remote',
  'git push <remote> <local-branch>:<remote-branch>': 'push local branch to different remote branch name push branch with different name on remote rename during push',
  'git push -u origin main --force-with-lease': 'push set upstream force safe to origin main first time force push main safely',
  'git push origin --delete <branch>': 'push delete specific remote branch origin remove branch from github after merge cleanup',
  'git push -u origin HEAD': 'push set upstream current branch to origin publish current branch push new branch to github first time',

  // ── Pull ──
  'git pull': 'pull download fetch merge changes from remote',
  'git pull <remote> <branch>': 'pull download from specific remote branch',
  'git pull --rebase': 'pull download rebase instead of merge clean history',
  'git pull --no-rebase': 'pull download merge default no rebase',
  'git pull --ff-only': 'pull fast-forward only fail if diverged',
  'git pull --no-ff': 'pull create merge commit no fast-forward',
  'git pull --squash': 'pull squash all changes into single commit',
  'git pull --all': 'pull download from all remotes',
  'git pull --depth <depth>': 'pull shallow download limited history',
  'git pull --autostash': 'pull auto stash unstash local changes',
  'git pull --no-commit': 'pull without auto commit review first',
  'git pull origin main': 'pull download from origin main branch',
  'git pull --rebase origin main': 'pull rebase from origin main branch',

  // ── Fetch ──
  'git fetch': 'fetch download remote changes without merge update refs',
  'git fetch <remote>': 'fetch download from specific remote',
  'git fetch --all': 'fetch download from all remotes',
  'git fetch --prune': 'fetch remove stale remote-tracking branches cleanup',
  'git fetch -p': 'fetch prune remove stale remote-tracking branches',
  'git fetch --tags': 'fetch download all tags from remote',
  'git fetch --no-tags': 'fetch download without tags',
  'git fetch --depth <depth>': 'fetch shallow download limited history',
  'git fetch --unshallow': 'fetch convert shallow to full clone complete history',
  'git fetch --dry-run': 'fetch preview simulate what would be downloaded',
  'git fetch <remote> <branch>': 'fetch download specific branch from remote',
  'git fetch --all --prune': 'fetch all remotes and clean stale branches',
  'git fetch origin': 'fetch download from origin remote',
  'git fetch origin main': 'fetch download main branch from origin',

  // ── Remote ──
  'git remote': 'remote list show configured remotes',
  'git remote -v': 'remote list show urls fetch push verbose',
  'git remote --verbose': 'remote list show urls fetch push verbose',
  'git remote add <name> <url>': 'remote add new remote repository connection',
  'git remote add origin <url>': 'remote add origin connect to remote repository',
  'git remote remove <name>': 'remote remove delete disconnect remote',
  'git remote rm <name>': 'remote remove delete disconnect remote',
  'git remote rename <old> <new>': 'remote rename change remote name',
  'git remote get-url <name>': 'remote get show url of remote',
  'git remote set-url <name> <url>': 'remote set change update url',
  'git remote show <name>': 'remote show detailed info branches tracking',
  'git remote prune <name>': 'remote prune remove stale tracking branches',

  // ── Stash ──
  'git stash': 'stash save temporarily store changes shelve work in progress save my work for later put changes aside switch branch without committing park changes',
  'git stash push': 'stash save temporarily store changes push save work for later',
  'git stash push -m "<message>"': 'stash save with description message label name my stash describe saved changes bookmark changes',
  'git stash push -- <file>': 'stash specific file only save one file for later stash single file',
  'git stash push -p': 'stash interactively select hunks patch mode choose what to stash partial stash',
  'git stash push --patch': 'stash interactively select hunks patch mode choose what to stash',
  'git stash push -u': 'stash include untracked files stash new files too save everything including new files',
  'git stash push --include-untracked': 'stash include untracked files save new files too',
  'git stash push -a': 'stash include all untracked ignored files save absolutely everything',
  'git stash push --all': 'stash include all untracked ignored files save everything',
  'git stash pop': 'stash pop restore apply and remove last stash get my saved changes back restore stashed work continue where i left off',
  'git stash pop stash@{<n>}': 'stash pop restore apply specific stash by index get back specific saved changes',
  'git stash apply': 'stash apply restore without removing keep stash reuse stashed changes apply saved work keep copy',
  'git stash apply stash@{<n>}': 'stash apply restore specific stash keep apply specific saved changes',
  'git stash list': 'stash list show all saved stashes see what is stashed view saved changes',
  'git stash show': 'stash show display changes in last stash summary see what was stashed preview stash',
  'git stash show -p': 'stash show display full diff patch details see full stash diff detailed stash view',
  'git stash show --patch': 'stash show display full diff patch details see full stash changes',
  'git stash show stash@{<n>}': 'stash show specific stash changes view specific stash',
  'git stash drop': 'stash drop remove delete last stash throw away stashed changes discard saved work',
  'git stash drop stash@{<n>}': 'stash drop remove delete specific stash remove old stash',
  'git stash clear': 'stash clear remove delete all stashes clean up all saved changes remove all stashes',
  'git stash branch <branch> stash@{<n>}': 'stash branch create new branch from stash apply make branch from saved changes start branch from stash',

  // ── Tag ──
  'git tag': 'tag list show all tags versions releases',
  'git tag <name>': 'tag create lightweight tag label',
  'git tag -a <name> -m "<message>"': 'tag create annotated tag with message',
  'git tag --annotate <name> -m "<message>"': 'tag create annotated tag with message',
  'git tag -d <name>': 'tag delete remove local tag',
  'git tag --delete <name>': 'tag delete remove local tag',
  'git tag -l "<pattern>"': 'tag list filter by pattern glob search',
  'git tag --list "<pattern>"': 'tag list filter by pattern glob search',
  'git tag -a <name> <commit>': 'tag create annotated tag on specific commit',
  'git tag -f <name>': 'tag force update replace existing tag',
  'git tag -v <name>': 'tag verify GPG signature signed tag',
  'git tag --verify <name>': 'tag verify GPG signature signed tag',
  'git tag -s <name> -m "<message>"': 'tag create signed GPG tag with message',
  'git tag --sort=-creatordate': 'tag list sort by date newest first',
  'git tag --sort=version:refname': 'tag list sort by version number semantic',

  // ── Reset ──
  'git reset': 'reset unstage undo remove from staging area',
  'git reset <file>': 'reset unstage specific file undo add',
  'git reset HEAD <file>': 'reset unstage specific file from HEAD',
  'git reset --soft HEAD~1': 'reset undo last commit keep changes staged',
  'git reset --mixed HEAD~1': 'reset undo last commit keep changes unstaged default',
  'git reset --hard HEAD~1': 'reset undo last commit discard all changes dangerous',
  'git reset --soft <commit>': 'reset move HEAD to commit keep changes staged',
  'git reset --mixed <commit>': 'reset move HEAD to commit keep changes unstaged',
  'git reset --hard <commit>': 'reset move HEAD to commit discard all changes dangerous',
  'git reset --hard': 'reset discard all changes working directory staging area',
  'git reset --hard HEAD': 'reset discard all changes to last commit clean',
  'git reset --hard origin/<branch>': 'reset match remote branch discard local changes',
  'git reset HEAD~<n>': 'reset undo last n commits keep changes unstaged',
  'git reset --keep <commit>': 'reset keep working directory changes safe',

  // ── Revert ──
  'git revert <commit>': 'revert undo commit create new inverse commit safe',
  'git revert HEAD': 'revert undo last commit with new commit',
  'git revert --no-commit <commit>': 'revert undo commit without auto committing stage only',
  'git revert --no-edit <commit>': 'revert undo commit default message no editor',
  'git revert -m 1 <merge-commit>': 'revert undo merge commit specify parent mainline',
  'git revert --abort': 'revert abort cancel stop revert in progress',
  'git revert --continue': 'revert continue resume after resolving conflict',
  'git revert HEAD~<n>..HEAD': 'revert undo range of last n commits',

  // ── Cherry-pick ──
  'git cherry-pick <commit>': 'cherry-pick apply specific commit from another branch copy',
  'git cherry-pick <commit1> <commit2>': 'cherry-pick apply multiple specific commits',
  'git cherry-pick --no-commit <commit>': 'cherry-pick apply without committing stage only',
  'git cherry-pick --edit <commit>': 'cherry-pick apply and edit commit message',
  'git cherry-pick --abort': 'cherry-pick abort cancel stop in progress',
  'git cherry-pick --continue': 'cherry-pick continue resume after resolving conflict',
  'git cherry-pick --skip': 'cherry-pick skip current commit continue next',
  'git cherry-pick <start>..<end>': 'cherry-pick apply range of commits',
  'git cherry-pick -x <commit>': 'cherry-pick apply and record original commit reference',

  // ── Clean ──
  'git clean -n': 'clean dry run preview untracked files to remove',
  'git clean --dry-run': 'clean dry run preview untracked files to remove',
  'git clean -f': 'clean force remove untracked files delete',
  'git clean --force': 'clean force remove untracked files delete',
  'git clean -fd': 'clean force remove untracked files and directories',
  'git clean -fX': 'clean force remove only ignored files',
  'git clean -fx': 'clean force remove ignored and untracked files',
  'git clean -i': 'clean interactive mode select files to remove',
  'git clean --interactive': 'clean interactive mode select files to remove',
  'git clean -fdx': 'clean force remove everything untracked ignored directories',

  // ── Show ──
  'git show <commit>': 'show display commit details changes diff',
  'git show HEAD': 'show display last commit details',
  'git show <commit>:<file>': 'show display file content at specific commit',
  'git show --stat <commit>': 'show commit statistics files changed summary',
  'git show --name-only <commit>': 'show commit changed file names only',
  'git show --name-status <commit>': 'show commit file names and change status',
  'git show <tag>': 'show display tag details annotation',
  'git show <branch>:<file>': 'show display file from specific branch',

  // ── Blame ──
  'git blame <file>': 'blame annotate show who changed each line author',
  'git blame -L <start>,<end> <file>': 'blame show who changed specific line range',
  'git blame -w <file>': 'blame ignore whitespace changes',
  'git blame --since="<date>" <file>': 'blame show changes since date',
  'git blame -C <file>': 'blame detect moved copied lines across files',
  'git blame -e <file>': 'blame show email instead of author name',

  // ── Bisect ──
  'git bisect start': 'bisect start binary search find bug commit',
  'git bisect bad': 'bisect mark current commit as bad broken',
  'git bisect good <commit>': 'bisect mark commit as good working',
  'git bisect reset': 'bisect reset end finish return to original branch',
  'git bisect bad <commit>': 'bisect mark specific commit as bad',
  'git bisect skip': 'bisect skip current commit untestable',
  'git bisect log': 'bisect show log history of steps',
  'git bisect run <command>': 'bisect automated run script test find bug',

  // ── Worktree ──
  'git worktree add <path> <branch>': 'worktree add create linked working tree directory',
  'git worktree list': 'worktree list show all linked working trees',
  'git worktree remove <path>': 'worktree remove delete linked working tree',
  'git worktree prune': 'worktree prune clean stale working tree info',
  'git worktree lock <path>': 'worktree lock prevent pruning',
  'git worktree unlock <path>': 'worktree unlock allow pruning',

  // ── Submodule ──
  'git submodule add <url>': 'submodule add include external repository dependency',
  'git submodule add <url> <path>': 'submodule add external repo at specific path',
  'git submodule init': 'submodule init initialize configure submodules',
  'git submodule update': 'submodule update checkout fetch latest submodule commits',
  'git submodule update --init': 'submodule init and update checkout',
  'git submodule update --init --recursive': 'submodule init update all nested recursive',
  'git submodule update --remote': 'submodule update to latest remote commit',
  'git submodule status': 'submodule status show state installed versions',
  'git submodule foreach <command>': 'submodule foreach run command in each submodule',
  'git submodule sync': 'submodule sync update url configuration',
  'git submodule deinit <path>': 'submodule deinit remove unregister submodule',
  'git submodule deinit --all': 'submodule deinit remove all unregister',

  // ── Config ──
  'git config --global user.name "<name>"': 'config set global username author name identity',
  'git config --global user.email "<email>"': 'config set global email address identity',
  'git config user.name "<name>"': 'config set local project username',
  'git config user.email "<email>"': 'config set local project email',
  'git config --list': 'config list show all settings configuration',
  'git config --global --list': 'config list show global settings configuration',
  'git config --local --list': 'config list show local repository settings',
  'git config --global core.editor "<editor>"': 'config set default editor vim nano vscode',
  'git config --global init.defaultBranch main': 'config set default branch name main',
  'git config --global alias.<name> "<command>"': 'config create alias shortcut custom command',
  'git config --unset <key>': 'config remove delete unset setting',
  'git config --global --unset <key>': 'config remove delete global setting',
  'git config --global color.ui auto': 'config enable color output terminal',
  'git config --global pull.rebase true': 'config set pull to rebase by default',
  'git config --global merge.ff false': 'config disable fast-forward merge by default',
  'git config --global credential.helper cache': 'config cache credentials password temporarily',
  'git config --global credential.helper store': 'config store credentials password permanently',
  'git config --global http.proxy <url>': 'config set http proxy corporate network',
  'git config --global core.autocrlf true': 'config line endings auto convert crlf windows',
  'git config --global core.autocrlf input': 'config line endings convert crlf lf unix mac',
  'git config --get <key>': 'config get show specific setting value',

  // ── Grep ──
  'git grep "<pattern>"': 'grep search find text pattern in tracked files',
  'git grep -n "<pattern>"': 'grep search with line numbers',
  'git grep -c "<pattern>"': 'grep search count matches per file',
  'git grep -l "<pattern>"': 'grep search show only matching file names',
  'git grep --name-only "<pattern>"': 'grep search show only matching file names',
  'git grep -i "<pattern>"': 'grep search case insensitive',
  'git grep -w "<pattern>"': 'grep search whole word only',
  'git grep -e "<pattern1>" --and -e "<pattern2>"': 'grep search multiple patterns AND both match',
  'git grep "<pattern>" <branch>': 'grep search in specific branch',
  'git grep "<pattern>" -- "*.js"': 'grep search in specific file types extension',

  // ── Archive ──
  'git archive --format=tar HEAD': 'archive create tarball export snapshot',
  'git archive --format=zip HEAD': 'archive create zip export snapshot download',
  'git archive --format=tar.gz HEAD': 'archive create compressed tarball gzip',
  'git archive --format=zip --output=<file> HEAD': 'archive create zip file export save',
  'git archive --format=tar --prefix=<dir>/ HEAD': 'archive create tar with directory prefix',
  'git archive <branch>': 'archive export specific branch snapshot',

  // ── Shortlog ──
  'git shortlog': 'shortlog summary commits grouped by author',
  'git shortlog -s': 'shortlog summary count only commits per author',
  'git shortlog -n': 'shortlog summary sorted by number of commits',
  'git shortlog -sn': 'shortlog summary count sorted most active contributors',
  'git shortlog -sne': 'shortlog summary count sorted with email addresses',
  'git shortlog --all': 'shortlog summary all branches contributors',

  // ── Describe ──
  'git describe': 'describe show nearest tag and distance human readable version',
  'git describe --tags': 'describe show nearest tag lightweight or annotated',
  'git describe --always': 'describe show tag or abbreviated commit hash',
  'git describe --abbrev=0': 'describe show only nearest tag name no distance',
  'git describe --long': 'describe show full format tag distance commit',

  // ── Reflog ──
  'git reflog': 'reflog show reference log history HEAD movements recovery',
  'git reflog show <branch>': 'reflog show specific branch reference log',
  'git reflog expire --expire=<time>': 'reflog remove old entries cleanup',
  'git reflog delete <ref>': 'reflog delete specific entry',
  'git reflog show --all': 'reflog show all references log',

  // ── Notes ──
  'git notes add -m "<message>"': 'notes add annotation comment to commit',
  'git notes add -m "<message>" <commit>': 'notes add annotation to specific commit',
  'git notes show': 'notes show display annotation current commit',
  'git notes show <commit>': 'notes show display annotation specific commit',
  'git notes edit': 'notes edit modify annotation current commit',
  'git notes edit <commit>': 'notes edit modify annotation specific commit',
  'git notes remove': 'notes remove delete annotation current commit',
  'git notes remove <commit>': 'notes remove delete annotation specific commit',
  'git notes list': 'notes list show all annotated commits',

  // ── Rev-parse ──
  'git rev-parse HEAD': 'rev-parse show full commit hash SHA current HEAD',
  'git rev-parse --short HEAD': 'rev-parse show short abbreviated commit hash',
  'git rev-parse --show-toplevel': 'rev-parse show repository root directory path',
  'git rev-parse --is-inside-work-tree': 'rev-parse check if inside git repository',
  'git rev-parse --git-dir': 'rev-parse show git directory path location',
  'git rev-parse --abbrev-ref HEAD': 'rev-parse show current branch name',

  // ── Ls-files / Ls-tree ──
  'git ls-files': 'ls-files list tracked files in repository',
  'git ls-files --others': 'ls-files list untracked files',
  'git ls-files --ignored --exclude-standard': 'ls-files list ignored files gitignore',
  'git ls-files --modified': 'ls-files list modified files',
  'git ls-files --deleted': 'ls-files list deleted files',
  'git ls-files --stage': 'ls-files list staged files with mode hash',
  'git ls-tree -r HEAD': 'ls-tree list all files in HEAD tree recursive',
  'git ls-tree --name-only HEAD': 'ls-tree list file names only',
  'git ls-tree -r <branch>': 'ls-tree list files in specific branch',
  'git ls-remote <url>': 'ls-remote list references in remote repository tags branches',
  'git ls-remote --heads <url>': 'ls-remote list remote branches heads only',
  'git ls-remote --tags <url>': 'ls-remote list remote tags only',
  'git ls-remote origin': 'ls-remote list references origin remote',

  // ── Rm / Mv ──
  'git rm <file>': 'rm remove delete file from working directory and index',
  'git rm --cached <file>': 'rm remove file from tracking index keep on disk untrack',
  'git rm -r <directory>': 'rm remove directory recursively from tracking',
  'git rm --cached -r <directory>': 'rm untrack directory keep on disk recursive',
  'git rm -f <file>': 'rm force remove delete file changed staged',
  'git mv <old> <new>': 'mv move rename file tracked by git',

  // ── Format-patch / Apply / Am ──
  'git format-patch <commit>': 'format-patch create patch file email from commit',
  'git format-patch -n <commit>': 'format-patch create n patches from commit',
  'git format-patch --root': 'format-patch create patches for all commits from root',
  'git format-patch <branch1>..<branch2>': 'format-patch create patches between branches',
  'git format-patch -1 <commit>': 'format-patch create single patch for specific commit',
  'git apply <patch>': 'apply apply patch file changes',
  'git apply --check <patch>': 'apply check test patch without applying dry run',
  'git apply --stat <patch>': 'apply show statistics of patch changes',
  'git am <patch>': 'am apply mailbox patch with commit create',
  'git am --abort': 'am abort cancel patch application',
  'git am --continue': 'am continue resume patch application after conflict',

  // ── Bundle ──
  'git bundle create <file> <refs>': 'bundle create package commits into file offline transfer',
  'git bundle verify <file>': 'bundle verify check integrity validity',
  'git bundle list-heads <file>': 'bundle list show references heads inside bundle',
  'git bundle unbundle <file>': 'bundle unbundle extract import from bundle file',

  // ── GC / Maintenance ──
  'git gc': 'gc garbage collection cleanup optimize repository',
  'git gc --prune=now': 'gc garbage collection remove unreachable objects immediately',
  'git gc --aggressive': 'gc aggressive deep optimization more thorough',
  'git gc --auto': 'gc automatic garbage collection if needed',
  'git prune': 'prune remove unreachable objects cleanup',
  'git fsck': 'fsck check integrity verify repository objects consistency',
  'git fsck --full': 'fsck full integrity check all objects',
  'git maintenance start': 'maintenance start automated background repository optimization',
  'git maintenance run': 'maintenance run optimization tasks now',
  'git maintenance stop': 'maintenance stop disable automated optimization',
  'git count-objects -vH': 'count-objects show repository size disk usage statistics',

  // ── gh auth ──
  'gh auth login': 'github authenticate login sign in connect account',
  'gh auth logout': 'github authenticate logout sign out disconnect',
  'gh auth status': 'github auth check status whoami logged in',
  'gh auth refresh': 'github auth refresh renew token credentials',
  'gh auth token': 'github auth show display current token',
  'gh auth setup-git': 'github auth configure git credential helper',

  // ── gh repo ──
  'gh repo create': 'github repository create new repo',
  'gh repo create <name>': 'github repository create with name',
  'gh repo create <name> --public': 'github repository create public visible',
  'gh repo create <name> --private': 'github repository create private hidden',
  'gh repo clone <repo>': 'github repository clone download copy',
  'gh repo fork <repo>': 'github repository fork copy contribute',
  'gh repo fork <repo> --clone': 'github repository fork and clone locally',
  'gh repo view': 'github repository view show details info readme',
  'gh repo view <repo>': 'github repository view specific repo details',
  'gh repo view --web': 'github repository open in browser web',
  'gh repo list': 'github repository list show user repos',
  'gh repo list <owner>': 'github repository list show specific user repos',
  'gh repo delete <repo>': 'github repository delete remove permanently',
  'gh repo delete <repo> --yes': 'github repository delete confirm remove',
  'gh repo rename <new-name>': 'github repository rename change name',
  'gh repo archive <repo>': 'github repository archive read-only',
  'gh repo edit': 'github repository edit modify settings',
  'gh repo sync': 'github repository sync upstream fork synchronize',

  // ── gh issue ──
  'gh issue create': 'github issue create new bug feature request report',
  'gh issue create --title "<title>" --body "<body>"': 'github issue create with title body',
  'gh issue create --label "<label>"': 'github issue create with label tag',
  'gh issue create --assignee "<user>"': 'github issue create assign to user',
  'gh issue list': 'github issue list show open issues',
  'gh issue list --state closed': 'github issue list show closed issues',
  'gh issue list --label "<label>"': 'github issue list filter by label',
  'gh issue list --assignee "<user>"': 'github issue list filter by assignee',
  'gh issue list --limit <n>': 'github issue list limit number results',
  'gh issue view <number>': 'github issue view show details specific',
  'gh issue view <number> --web': 'github issue view open in browser',
  'gh issue close <number>': 'github issue close resolve done',
  'gh issue reopen <number>': 'github issue reopen open again',
  'gh issue edit <number>': 'github issue edit modify update',
  'gh issue comment <number> --body "<comment>"': 'github issue comment add reply',
  'gh issue delete <number>': 'github issue delete remove permanently',
  'gh issue transfer <number> <repo>': 'github issue transfer move to another repo',
  'gh issue pin <number>': 'github issue pin important sticky top',
  'gh issue unpin <number>': 'github issue unpin remove from top',
  'gh issue status': 'github issue status show assigned mentioned created',
  'gh issue develop <number>': 'github issue develop create branch linked',

  // ── gh pr ──
  'gh pr create': 'github pull request create new submit open pr make a pull request create pr submit code for review send changes for review raise a pr open a pr create pr from branch create pull request from feature branch',
  'gh pr create --title "<title>" --body "<body>"': 'github pull request create with title body create pr with title and body description create pr with message open pull request with description submit pr with details',
  'gh pr create --draft': 'github pull request create draft work in progress open draft pr wip pull request not ready for review create pr as draft',
  'gh pr create --base <branch>': 'github pull request create target base branch create pr to main create pr to master create pr from branch to main merge into specific branch pr targeting main pr targeting develop',
  'gh pr create --head <branch>': 'github pull request create source head branch create pr from specific branch open pr from feature branch submit pr from my branch',
  'gh pr create --reviewer "<user>"': 'github pull request create add reviewer create pr and request review assign reviewer to pr ask someone to review',
  'gh pr create --assignee "<user>"': 'github pull request create assign user assign pr to someone create pr assigned to teammate',
  'gh pr create --label "<label>"': 'github pull request create add label create pr with label tag pr with category',
  'gh pr create --fill': 'github pull request create auto fill title body from commits quick pr auto generate description create pr from commit messages',
  'gh pr create --web': 'github pull request create in browser web open pr creation page in browser create pr on github website',
  'gh pr list': 'github pull request list show open PRs see all pull requests view open prs check pending reviews',
  'gh pr list --state merged': 'github pull request list merged see merged prs view completed pull requests history',
  'gh pr list --state closed': 'github pull request list closed see closed rejected prs',
  'gh pr list --label "<label>"': 'github pull request list filter label find prs by label category',
  'gh pr list --assignee "<user>"': 'github pull request list filter assignee find my prs see prs assigned to me',
  'gh pr list --limit <n>': 'github pull request list limit results show only n pull requests',
  'gh pr view <number>': 'github pull request view show details see pr info check pr details read pr description',
  'gh pr view <number> --web': 'github pull request view open browser see pr on github website open in browser',
  'gh pr checkout <number>': 'github pull request checkout switch to PR branch locally test a pr download pr code review pr locally get pr code on my machine',
  'gh pr merge <number>': 'github pull request merge accept approve merge pr accept changes complete pr close pr with merge',
  'gh pr merge <number> --merge': 'github pull request merge commit regular merge pr normal merge',
  'gh pr merge <number> --squash': 'github pull request merge squash combine merge pr as single commit clean merge squash and merge pr',
  'gh pr merge <number> --rebase': 'github pull request merge rebase linear rebase and merge pr clean linear history',
  'gh pr merge <number> --delete-branch': 'github pull request merge and delete branch cleanup merge and remove branch auto cleanup after merge',
  'gh pr close <number>': 'github pull request close reject decline close pr without merging reject pr cancel pr',
  'gh pr reopen <number>': 'github pull request reopen open again reopen closed pr',
  'gh pr review <number>': 'github pull request review approve comment review someone else pr give feedback on pr',
  'gh pr review <number> --approve': 'github pull request review approve LGTM approve pr looks good accept changes give thumbs up',
  'gh pr review <number> --comment --body "<comment>"': 'github pull request review comment feedback leave comment on pr add review feedback give suggestion',
  'gh pr review <number> --request-changes --body "<comment>"': 'github pull request review request changes ask for fixes request modifications reject with feedback needs work',
  'gh pr diff <number>': 'github pull request diff show changes see what changed in pr view pr diff code changes',
  'gh pr checks <number>': 'github pull request checks CI status tests see if pr checks passed view CI results pr pipeline status',
  'gh pr ready <number>': 'github pull request mark ready for review undraft convert draft pr to ready mark pr as ready for review',
  'gh pr comment <number> --body "<comment>"': 'github pull request comment add reply comment on pr discuss on pull request leave feedback',
  'gh pr edit <number>': 'github pull request edit modify update change pr title update pr description edit pull request details',
  'gh pr status': 'github pull request status show created review requested see my prs check pr status what prs need my review',

  // ── gh gist ──
  'gh gist create <file>': 'github gist create share code snippet',
  'gh gist create <file> --public': 'github gist create public visible snippet',
  'gh gist create <file> -d "<description>"': 'github gist create with description',
  'gh gist list': 'github gist list show all gists',
  'gh gist view <id>': 'github gist view show content',
  'gh gist edit <id>': 'github gist edit modify update',
  'gh gist delete <id>': 'github gist delete remove',
  'gh gist clone <id>': 'github gist clone download locally',

  // ── gh release ──
  'gh release create <tag>': 'github release create new version publish',
  'gh release create <tag> --title "<title>"': 'github release create with title',
  'gh release create <tag> --notes "<notes>"': 'github release create with notes description',
  'gh release create <tag> --draft': 'github release create draft unpublished',
  'gh release create <tag> --prerelease': 'github release create pre-release beta',
  'gh release create <tag> --generate-notes': 'github release create auto generate changelog notes',
  'gh release create <tag> <files>': 'github release create with assets attachments files',
  'gh release list': 'github release list show all releases versions',
  'gh release view <tag>': 'github release view show details specific',
  'gh release view <tag> --web': 'github release view open in browser',
  'gh release download <tag>': 'github release download assets files',
  'gh release delete <tag>': 'github release delete remove version',
  'gh release edit <tag>': 'github release edit modify update',
  'gh release upload <tag> <files>': 'github release upload add assets files',

  // ── gh workflow / run ──
  'gh workflow list': 'github workflow list show actions CI/CD pipelines',
  'gh workflow view <name>': 'github workflow view show details runs',
  'gh workflow view <name> --web': 'github workflow view open in browser',
  'gh workflow run <name>': 'github workflow run trigger dispatch start',
  'gh workflow enable <name>': 'github workflow enable activate turn on',
  'gh workflow disable <name>': 'github workflow disable deactivate turn off',
  'gh run list': 'github run list show action workflow runs',
  'gh run list --workflow <name>': 'github run list filter by workflow',
  'gh run view <id>': 'github run view show details logs',
  'gh run view <id> --web': 'github run view open in browser',
  'gh run view <id> --log': 'github run view show full logs',
  'gh run watch <id>': 'github run watch live monitor progress',
  'gh run rerun <id>': 'github run rerun retry failed action',
  'gh run cancel <id>': 'github run cancel stop action workflow',
  'gh run download <id>': 'github run download artifacts files',

  // ── gh label ──
  'gh label create <name>': 'github label create new tag',
  'gh label create <name> --color "<color>"': 'github label create with color',
  'gh label create <name> --description "<desc>"': 'github label create with description',
  'gh label list': 'github label list show all labels tags',
  'gh label edit <name>': 'github label edit modify update',
  'gh label delete <name>': 'github label delete remove',
  'gh label clone <repo>': 'github label clone copy labels from another repo',

  // ── gh api ──
  'gh api <endpoint>': 'github api call request REST endpoint',
  'gh api <endpoint> --method POST': 'github api POST request create',
  'gh api <endpoint> --method PUT': 'github api PUT request update',
  'gh api <endpoint> --method DELETE': 'github api DELETE request remove',
  'gh api <endpoint> -f <key>=<value>': 'github api request with field data parameter',
  'gh api <endpoint> --jq "<query>"': 'github api request filter output jq JSON',
  'gh api <endpoint> --paginate': 'github api request paginate all pages results',
  'gh api graphql -f query="<query>"': 'github api graphql request query',
  'gh api <endpoint> -H "Accept: application/vnd.github+json"': 'github api request custom header accept',

  // ── gh ssh-key / gpg-key ──
  'gh ssh-key add <file>': 'github ssh key add upload public key authentication',
  'gh ssh-key add <file> --title "<title>"': 'github ssh key add with title label',
  'gh ssh-key list': 'github ssh key list show all keys',
  'gh ssh-key delete <id>': 'github ssh key delete remove',
  'gh gpg-key add <file>': 'github gpg key add upload signing key',
  'gh gpg-key list': 'github gpg key list show all keys',
  'gh gpg-key delete <id>': 'github gpg key delete remove',

  // ── gh alias / extension / config ──
  'gh alias set <name> "<command>"': 'github alias create shortcut custom command',
  'gh alias list': 'github alias list show all aliases shortcuts',
  'gh alias delete <name>': 'github alias delete remove shortcut',
  'gh config set <key> <value>': 'github config set setting preference',
  'gh config get <key>': 'github config get show setting preference',
  'gh config list': 'github config list show all settings',
  'gh extension install <repo>': 'github extension install add plugin',
  'gh extension list': 'github extension list show installed plugins',
  'gh extension upgrade <name>': 'github extension upgrade update plugin',
  'gh extension remove <name>': 'github extension remove uninstall plugin'
}

/**
 * Get the hidden description for a command.
 * Returns empty string if no description exists.
 */
export function getDescription(command) {
  return descriptions[command] || ''
}

// Stop words that are filtered out from search queries.
// These are common filler words that would break natural language matching.
const STOP_WORDS = new Set([
  'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'do', 'does', 'did', 'doing', 'have', 'has', 'had', 'having',
  'i', 'me', 'my', 'we', 'our', 'you', 'your',
  'it', 'its', 'this', 'that', 'these', 'those',
  'of', 'in', 'on', 'at', 'by', 'up', 'as', 'if', 'or', 'so',
  'to', 'from', 'into', 'onto', 'for', 'with', 'without',
  'and', 'but', 'not', 'no', 'nor',
  'how', 'what', 'which', 'who', 'whom', 'when', 'where', 'why',
  'can', 'could', 'will', 'would', 'shall', 'should', 'may', 'might', 'must',
  'want', 'need', 'like', 'using', 'use', 'way',
  'some', 'any', 'all', 'each', 'every', 'both',
  'just', 'also', 'very', 'too', 'only', 'then', 'than'
])

/**
 * Check if a command matches a search query by checking both
 * the command text AND the hidden description.
 * Stop words are filtered out so natural language queries work.
 * e.g. "create a pr from branch to main" → matches on "create", "pr", "branch", "main"
 */
export function matchesSearch(command, query) {
  const q = query.toLowerCase().trim()
  if (!q) return true
  
  const cmdLower = command.toLowerCase()
  const descLower = (descriptions[command] || '').toLowerCase()
  
  // Split query into words and filter out stop words
  const queryWords = q.split(/\s+/).filter(word => !STOP_WORDS.has(word))
  
  // If all words were stop words, do a raw full-text match
  if (queryWords.length === 0) {
    return cmdLower.includes(q) || descLower.includes(q)
  }
  
  // All meaningful query words must match either the command or description
  return queryWords.every(word => 
    cmdLower.includes(word) || descLower.includes(word)
  )
}
